# Generated by Django 2.1 on 2018-08-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180818_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
