# Generated by Django 2.1 on 2018-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180823_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Enter a date between now and 4 weeks (default 3).', null=True),
        ),
    ]
